// Generated by scripts/prepare_boxing_body.py. CMU 13_17, frames 170..300.
// NSF EIA-0196217; source SHA256: 5eba9811c5031d661f013e7269233c21878a9b70be0a1a4bed49baaec0161634
// Hip/chest timing only; not a full-body motion capture retarget.
namespace UltramanGame.Core
{
    internal static class BoxingBodySamples
    {
        internal static readonly float[] Hip = { 0.00000f, -0.46954f, -1.42945f, -2.76175f, -2.42835f, -1.99240f, -0.93128f, 3.01844f, 9.55461f, 14.78549f, 16.71270f, 18.65743f, 20.00029f, 20.85739f, 20.69773f, 19.67339f, 18.56208f, 17.57407f, 16.58802f, 15.60605f, 14.49435f, 13.02710f, 11.27408f, 9.53260f, 7.96831f, 6.54562f, 5.17483f, 3.81354f, 2.69189f, 1.75126f, 1.09873f, 0.61715f, 0.00000f };
        internal static readonly float[] Chest = { 0.00000f, -0.68665f, -0.49153f, 0.49370f, 0.14480f, 0.00980f, -0.08070f, -0.93612f, -1.03871f, 1.84231f, 4.93848f, 5.66539f, 4.85937f, 3.97424f, 3.61533f, 3.93722f, 4.24095f, 4.38810f, 4.28380f, 3.94225f, 3.89017f, 3.74429f, 3.32741f, 2.79772f, 1.88272f, 1.19976f, 0.68071f, 0.52705f, 0.16233f, 0.04900f, -0.16095f, -0.30566f, 0.00000f };
    }
}
