"""Extract bounded hip/chest timing from CMU 13_17 (boxing), not a whole rig.

CMU data: http://mocap.cs.cmu.edu/ (NSF EIA-0196217).
BVH conversion: https://github.com/una-dinosauria/cmu-mocap/blob/master/data/013/13_17.bvh
Free for use in products; do not resell the motion data itself.
"""
import argparse
import hashlib
from pathlib import Path

import numpy as np
from inspect_mocap_bvh import read_bvh


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('source', type=Path)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    joints, positions, _, _ = read_bvh(args.source)
    names = [j['name'] for j in joints]
    def p(name):
        return positions[:, names.index(name)]
    def yaw(a, b):
        axis = p(a) - p(b)
        return np.degrees(np.unwrap(np.arctan2(axis[:, 2], -axis[:, 0])))
    first, contact, last = 170, 238, 300
    phase = np.linspace(0, 1, 33)
    # Contact stays at the existing .12 second gameplay beat. Retraction is
    # allowed more time; source world travel is deliberately not retargeted.
    source_frames = np.where(phase <= 1/3,
                             first + (contact-first)*phase*3,
                             contact + (last-contact)*(phase-1/3)*1.5)
    hip = yaw('RightUpLeg', 'LeftUpLeg')
    chest = yaw('RightArm', 'LeftArm') - hip
    arrays = []
    for name, raw, gain in [('Hip', hip, .24), ('Chest', chest, .26)]:
        raw = raw - raw[first]
        # Remove the source actor's change of facing so a completed punch
        # returns exactly to the live ready/queued opposite-hand pose.
        values = np.interp(source_frames, np.arange(len(raw)), raw)
        values -= (source_frames-first)/(last-first)*raw[last]
        values *= gain
        values[0] = values[-1] = 0
        if np.max(np.abs(values)) > 25:
            raise ValueError('Unexpected boxing source rotation')
        arrays.append('        internal static readonly float[] ' + name + ' = { ' +
                      ', '.join(f'{x:.5f}f' for x in values) + ' };')
    text = ('// Generated by scripts/prepare_boxing_body.py. CMU 13_17, frames 170..300.\n'
            '// NSF EIA-0196217; source SHA256: ' + hashlib.sha256(args.source.read_bytes()).hexdigest() + '\n'
            '// Hip/chest timing only; not a full-body motion capture retarget.\n'
            'namespace UltramanGame.Core\n{\n    internal static class BoxingBodySamples\n    {\n' +
            '\n'.join(arrays) + '\n    }\n}\n')
    args.output.write_text(text)


if __name__ == '__main__':
    main()
